# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "zakaria-spotify-bucket"
    dynamodb_table = "terraform-state-locks"
    encrypt        = true
    key            = "hack-tuah/staging/terraform.tfstate"
    region         = "us-east-1"
  }
}
